name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run coverage
      - run: pnpm run build
      - run: pnpm run debug-imports
      - run: pnpm run bench
      - run: pnpm pack
      - run: pnpm publint
